/*
 * DeleteUser.java
 * Created on January 24, 2007, 5:07 AM
 */

package mainserver;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.net.*;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.swing.JOptionPane;
import messages.ServerMessages;

/**
 * @author  Nissimzo
 */

public class DeleteUser extends javax.swing.JFrame {
    private String DB_Server;           // the DataBase server ip
    private int DB_port;                // the DataBase server port
    private Socket DB_socket;           // the DataBase server socket
    private DesEncrypter DBencrypter;   // the encryption class
    private ObjectInputStream DBinput;  // the DataBase input sockect stream
    private ObjectOutputStream DBoutput;// the DataBase output sockect stream
    
    /** Creates new form DeleteUser */
    
    public DeleteUser(String server,int port) {
        super("Delete User");
        DB_Server = server;
        DB_port = port;
        initComponents();
        setLocationRelativeTo(null); //Display the window center it.
    }
    
    public DeleteUser(String server,int port,String item ) {
        super("Delete User");
        DB_Server = server;
        DB_port = port;
        initComponents();
        UserNametext.setText(item);
        setLocationRelativeTo(null); //Display the window center it.
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UserNametext = new javax.swing.JTextField();
        DeleteButt = new javax.swing.JButton();
        BackButt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jLabel1.setText("User Name:");

        DeleteButt.setText("Delete");
        DeleteButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DeleteButtMousePressed(evt);
            }
        });

        BackButt.setText("Back");
        BackButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserNametext, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(DeleteButt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(BackButt)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BackButt, DeleteButt});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(UserNametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButt)
                    .addComponent(DeleteButt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void DeleteButtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtMousePressed
        
        if(UserNametext.getText().equals(""))
            return;
        try {
            // server must connect to the database server and ask about the user
            DB_socket = new Socket(DB_Server,DB_port);
            OutputStream out = DB_socket.getOutputStream();
            DBoutput = new ObjectOutputStream(out);
            InputStream in = DB_socket.getInputStream();
            DBinput = new ObjectInputStream(in);
            
            //genarte a new key and send it to database
            if(!GenerateSendKeyDB())
                return;
            
            // send to the DB Server the Admin user + admin Password
            sendDBData(ServerMessages.ADMINNAME);
            sendDBData(ServerMessages.ADMINPASSWORD);
            
            // wait for reply if success or not
            String Data = RecivedString();
            if(!Data.equals(ServerMessages.GRANT_ACCESS)) {
                //if not send that fail ...
                sendDBData(ServerMessages.CANCEL_CONNECTION);
                return;
            }
            //TELL THE DATABASE THAT WE WANNA CHECK USER NAME AND PASSWORD
            sendDBData(ServerMessages.DELETE_USER);
            // SEND USER NAME
            sendDBData(UserNametext.getText());
            
            //get the answer
            Data = RecivedString();
            if(Data.equals(ServerMessages.USER_IS_DELETED))
                JOptionPane.showMessageDialog(this, "User : [" + UserNametext.getText() + "] Deleted.","Delete User",JOptionPane.CANCEL_OPTION);
            else
                JOptionPane.showMessageDialog(this,"User : [" + UserNametext.getText() + "] Can't Delete.","Delete User",JOptionPane.CANCEL_OPTION);
            DB_socket.close();
            this.dispose();
        } catch (UnknownHostException ex) {
            JOptionPane.showMessageDialog(this,"Can't Connect to Data Base Server.","Delete User",JOptionPane.CANCEL_OPTION);
            ex.printStackTrace();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,"Can't Connect to Data Base Server.","Delete User",JOptionPane.CANCEL_OPTION);
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_DeleteButtMousePressed
    
    private void BackButtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtMouseClicked
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BackButtMouseClicked
    
    public void sendDBData(String str) throws IOException {
        /*******************************************************************
         * The sendData() method in the client sends data to the server
         ***************************************************************** */
        //output.println( str );
        DBoutput.writeObject(DBencrypter.encrypt(str));//sending to the user a string as object
    }
    
    public String RecivedString() throws IOException, ClassNotFoundException{
        /*******************************************************************
         * The RecivedString() method in the client Recived data from server
         ***************************************************************** */
        //output.println( str );
        String rec = (String) DBinput.readObject();
        return DBencrypter.decrypt(rec);
    }
    
    private boolean GenerateSendKeyDB() {
        try{
            // Generate a temporary key. In practice, you would save this key.
            // See also e464 Encrypting with DES Using a Pass Phrase.
            SecretKey key = KeyGenerator.getInstance("DES").generateKey();
            DBoutput.writeObject(key);//sending the key to the user
            DBencrypter = new DesEncrypter(key);
            return true;
        }catch(Exception e) {
            return false;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButt;
    private javax.swing.JButton DeleteButt;
    private javax.swing.JTextField UserNametext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
